//Action Types

// Request Constants
export const REQUEST_INIT = 'REQUEST_INIT';
export const REQUEST_COMPLETE = 'REQUEST_COMPLETE';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_NOTFOUND = 'REQUEST_NOTFOUND';
export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
